versions:
  "6.10.2":
    folder: 6.x.x
  "6.10.1":
    folder: 6.x.x
  "6.10.0":
    folder: 6.x.x
  "6.9.1":
    folder: 6.x.x
  "6.8.3":
    folder: 6.x.x
  "6.7.3":
    folder: 6.x.x
  "6.7.0":
    folder: 6.x.x
  "6.6.3":
    folder: 6.x.x
  "6.5.3":
    folder: 6.x.x
  "5.15.18":
    folder: 5.x.x
  "5.15.16":
    folder: 5.x.x
