versions:
  "8.18.0":
    folder: all
  "8.17.0":
    folder: all
  "8.16.0":
    folder: all
  "8.15.0":
    folder: all
  "8.14.1":
    folder: all
  "8.13.0":
    folder: all
  "8.12.1":
    folder: all
  "8.11.1":
    folder: all
  "8.11.0":
    folder: all
  "8.10.1":
    folder: all
  "8.10.0":
    folder: all
  "8.9.1":
    folder: all
  "8.9.0":
    folder: all
  "8.8.0":
    folder: all
  "8.6.0":
    folder: all
  "8.5.0":
    folder: all
  "8.4.0":
    folder: all
  "8.2.1":
    folder: all
  "8.1.2":
    folder: all
  "8.0.1":
    folder: all
  "7.88.1":
    folder: all
