versions:
  "0.31.0":
    folder: all
  "0.30.1":
    folder: all
  "0.29.0":
    folder: all
  "0.28.0":
    folder: all
  "0.26.0":
    folder: all
  "0.24.0":
    folder: all
  "0.20.1":
    folder: all
